model:
  prompt_template: "a photo of x x"
  clip_model: "ViT-L/14"
  res_w: 0.5
  width_img: 1024
  width_txt: 768

train:
  dataset: vaw-czsl
  dataset_path: "../../../dataset/vaw-czsl"
  lr: 0.0005
  dropout: 0.3
  weight_decay: 0.00001
  context_length: 8
  train_batch_size: 1
  gradient_accumulation_steps: 2
  seed: 0
  epochs: 30
  epoch_start: 0
  epoch_round: 3
  ent_weight: False
  update: False
  save_path: data/model/vaw-czsl/zzsp
  best_model_metric: best_loss     #best_unseen  best_seen AUC best_loss best_hm
  save_model: True
  load_model: False     # False or model path
  att_obj_w: 0.01
  sp_w: 0.1
  log_id: "This is the training process of zzsp"

test:
  eval_batch_size: 8
  open_world: False
  load_model: "./data/model/vaw-czsl/zzsp/zzsp_best.pt"
  topk: 1
  text_encoder_batch_size: 36
  threshold: 0.4
  threshold_trials: 50
  bias: 0.001